import type { NextPage } from "next";
import styles from "../styles/Home.module.css";
import Head from "next/head";
import Menu from "../components/Menu";
import ProjectsList from "../components/ProjectsList";

const Home: NextPage = () => (
  <div className="d-flex">
    <Head>
      <title>BugTracker</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <Menu />

    <div className={styles.header}>
      <h2 className="m-4">Dashboard</h2>
      <ProjectsList></ProjectsList>
    </div>
  </div>
);

export default Home;
